name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker docker Login
      env: 
        DOCKER_USERNAME:  ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD:  ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wfajraoui/docker-s2-python:$(date +%s)
   
      
    - name: Push Docker Image to Docker Hub
      run: docker push ${{secrets.DOCKER_USERNAME}}/docker-s2-python:$(date +%s)
